---
- name: Installing Homebrew Cask Packages (Virtualbox)
  ansible.builtin.homebrew_cask:
    name:
      - virtualbox
    state: present
  when: vagrant_vbox.install

- name: Installing Homebrew Cask Packages (VAGRANT)
  ansible.builtin.homebrew_cask:
    name:
      - vagrant
      - vagrant-manager
    state: present
