---
# - name: Add Oracle VirtualBox GPG apt Key
#   apt_key:
#     url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
#     state: present

# - name: Add Oracle VirtualBox repository
#   apt_repository:
#     repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
#     state: present

- name: Add Oracle VirtualBox repository
  apt_repository:
    repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse"
    state: present

- name: Installing apt Packages (VirtualBox)
  ansible.builtin.apt:
    pkg:
      - "virtualbox" # -{{ vagrant_vbox_version }}"
      - virtualbox—ext–pack
    state: present
    update_cache: true
  become: true

- name: Add users to vboxusers group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: vboxusers
    append: true
  loop: "{{ vboxusers_group_members }}"
  become: true
