---
- name: Install Virtualbox (Linux)
  include_tasks: Deb_vbox.yml
  when: vagrant_vbox.install

- name: Add HashiCorp GPG apt Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp releases repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Installing apt Packages (VAGRANT)
  ansible.builtin.apt:
    pkg: vagrant
    state: present
    update_cache: true
  become: true
