---
- include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: Darwin.yml
  when: ansible_os_family == 'Darwin'

- include_tasks: Windows.yml
  when: ansible_os_family == 'Windows'

- name: Check VM storage directory setting
  ansible.builtin.command: vboxmanage list systemproperties | grep folder
  register: current_vm_dir
  notify:
    - Set VM storage directory
  when: vagrant_vboxvm_storage_dir is defined and vagrant_vboxvm_storage_dir == True
