---
- name: Install Chocolatey packages (VirtualBox)
  chocolately.win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items: "{{ vagrant_choco_pkgs.virtualbox }}"
  when: install_vbox

- name: Install Hyper-V
  community.windows.win_feature:
    name: Microsoft-Hyper-V
    state: present
    include_sub_features: true
    include_management_tools: true
  when: vagrant_install_hyperv

- name: Install Chocolatey packages (VAGRANT)
  chocolately.win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items: "{{ vagrant_choco_pkgs.vagrant }}"
