---
- name: Set VM storage directory
  become: true
  ansible.builtin.command: vboxmanage setproperty machinefolder {{ vagrant_vboxvm_storage_dir }}
  when: current_vm_dir != vagrant_vboxvm_storage_dir
